# Generated by Django 2.1.7 on 2019-09-12 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_permission', '0003_user_sign'),
        ('blog', '0002_auto_20190912_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account_permission.User', verbose_name='所属用户'),
            preserve_default=False,
        ),
    ]
