# Generated by Django 2.1.7 on 2019-09-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='count',
            field=models.IntegerField(default=0, verbose_name='当前分类有多少文章'),
        ),
    ]
