# Generated by Django 2.1.7 on 2019-09-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_permission', '0003_user_sign'),
        ('blog', '0004_auto_20190912_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'user')},
        ),
    ]
