# Generated by Django 2.1.7 on 2019-09-22 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='班级名称')),
                ('number', models.IntegerField(verbose_name='班级人数')),
            ],
            options={
                'verbose_name': '班级表',
                'verbose_name_plural': '班级表',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='课程名称')),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_system.Classes', verbose_name='所属班级')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='成绩')),
                ('note', models.TextField(verbose_name='评语')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_system.Courses', verbose_name='课程')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='学号')),
                ('name', models.CharField(max_length=16, verbose_name='学生姓名')),
                ('age', models.IntegerField(verbose_name='学生年龄')),
                ('hometown', models.CharField(max_length=32, verbose_name='学生家乡')),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_system.Classes', verbose_name='所属班级')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='老师姓名')),
                ('age', models.IntegerField(verbose_name='老师年龄')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_system.Students', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_system.Teachers', verbose_name='任课老师'),
        ),
    ]
