# Generated by Django 2.1.7 on 2019-09-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='number',
            field=models.IntegerField(default=0, verbose_name='班级人数'),
        ),
    ]
