# Generated by Django 2.1.7 on 2019-09-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_system', '0002_auto_20190922_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='number',
            field=models.CharField(max_length=32, verbose_name='学号'),
        ),
    ]
