# Generated by Django 2.1.7 on 2019-09-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_system', '0003_auto_20190922_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='评语'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('course', 'student')},
        ),
    ]
