# Generated by Django 2.1.7 on 2019-09-11 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='代码行数')),
                ('date', models.DateField(auto_now=True, verbose_name='日期')),
                ('file', models.CharField(max_length=510, verbose_name='文件')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_permission.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '代码统计表',
                'verbose_name_plural': '代码统计表',
            },
        ),
    ]
