# Generated by Django 2.1.7 on 2019-09-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_permission', '0002_auto_20190912_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='个性签名'),
        ),
    ]
