# Generated by Django 2.1.7 on 2019-09-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='sail_count',
            field=models.IntegerField(default=0, verbose_name='购买人数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='sail_count',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
