# Generated by Django 2.1.7 on 2019-09-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0003_auto_20190930_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='img',
            field=models.CharField(blank=True, max_length=510, null=True, verbose_name='课程图片'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='type',
            field=models.IntegerField(choices=[(0, '线上'), (1, '线下')], verbose_name='课程类型'),
        ),
    ]
