# Generated by Django 2.1.7 on 2019-10-02 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0004_auto_20190930_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
