# Generated by Django 2.1.7 on 2019-10-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0005_auto_20191002_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='数量'),
            preserve_default=False,
        ),
    ]
