# Generated by Django 2.1.7 on 2019-10-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0006_orders_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
