# Generated by Django 2.1.7 on 2019-10-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pottery', '0007_remove_orders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pay_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='第三方支付单号'),
        ),
    ]
